version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "63790:6379"
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    hostname: mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./mysql-data:/var/lib/mysql
