server:
  port: 28080

spring:
  profiles:
    active: global-cache-strategy
  redis:
    host: localhost
    port: 63790
  datasource:
    url: jdbc:mysql://localhost:33061/test?useSSL=false&serverTimezone=UTC
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
